from astropy.io import fits
from astropy.coordinates import Angle, SkyCoord
from astropy.time import Time
import astropy.units as u
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import numpy as np
import glob
import pandas as pd
import os
import math
import sqlite3
import io
import re
import warnings
from PIL import Image
from pathlib import Path
from find_source import summary, _fits_data_index


def _interpolation_kernel(s: float):
    """Evaluate the Keys cubic convolution interpolation kernel.

    Parameters
    ----------
    s : float
        Dimensionless distance from the interpolation node.

    Returns
    -------
    float
        Value of the interpolation kernel at `s`.

    References
    ----------
    .. [1] R. G. Keys, "Cubic Convolution Interpolation for Digital Image
       Processing," IEEE Transactions on Acoustics, Speech, and Signal
       Processing, 29(6), 1153-1160, 1981.
    """
    dist = abs(s)
    if dist < 1:
        return (3/2 * (dist**3) - 5/2 * (dist**2) + 1)
    if dist < 2:
        return (-1/2 * (dist**3) + 5/2 * (dist**2) - 4 * dist + 2)
    return 0


def _interpolation_function(
    x: float,
    node_x: list,
    node_val: list,
) -> float:
    """Interpolate values using Keys cubic convolution interpolation.

    Parameters
    ----------
    x : float
        Position at which to evaluate the interpolation.
    node_x : list
        Positions of the interpolation nodes. The nodes must be uniformly
        spaced and contain at least three elements.
    node_val : list
        Values associated with `node_x`. Must have the same length as
        `node_x`.

    Returns
    -------
    float
        Interpolated value at `x`.

    Raises
    ------
    ValueError
        If fewer than three elements are provided in `node_x`; `node_x` and
        `node_val` have different lengths; or if `node_x` is not uniformly
        spaced.

    Notes
    -----
    Boundary values outside the interpolation domain are determined using
    the third-order boundary conditions described by Keys [1]_.

    References
    ----------
    .. [1] R. G. Keys, "Cubic Convolution Interpolation for Digital Image
       Processing," IEEE Transactions on Acoustics, Speech, and Signal
       Processing, 29(6), 1153-1160, 1981.
    """
    num_nodes = len(node_x)
    N = num_nodes - 1

    if len(node_val) != num_nodes:
        raise ValueError(
            f"The number of nodes given ({num_nodes}) does not match the "
            f"number of node values given ({len(node_val)})."
        )
    if num_nodes < 3:
        raise ValueError(
            f"At least 3 interpolation nodes are required. Got {num_nodes}."
        )
    h = node_x[1] - node_x[0]
    if not np.allclose(np.diff(node_x), h):
        raise ValueError("Nodes are not uniformly spaced.")

    # Apply the third-order boundary conditions derived by Keys (1981).
    node_neg1 = node_x[0] - h
    node_Nplus1 = node_x[N] + h
    c_neg1 = node_val[2] - 3 * node_val[1] + 3 * node_val[0]
    c_Nplus1 = 3*node_val[N] - 3 * node_val[N-1] + 3 * node_val[N-2]

    interpolated_val = c_neg1 * _interpolation_kernel((x - node_neg1) / h)
    for k in range(num_nodes):
        s = (x - node_x[k]) / h
        interpolated_val += node_val[k] * _interpolation_kernel(s)
    interpolated_val += c_Nplus1 * _interpolation_kernel((x - node_Nplus1) / h)

    return float(interpolated_val)


def thumbnail(
    fits_file: str | Path,
    peak_coord: tuple,
    radius_buffer: float,
    pts_bw_nodes: int = 4,
) -> bytes:
    """Create a Keys cubic convolution interpolated image thumbnail.

    The thumbnail is centered approximately on a source and generated by
    applying cubic convolution interpolation between the pixels of the
    selected image region.

    Parameters
    ----------
    fits_file : str | Path
        The path of the FITS file that contains the image.
    peak_coord : tuple
        A tuple `(x, y)` containing the x- and y-coordinates of the source, in
        arcseconds relative to the field center.
    radius_buffer : float
        Additional radius, in arcsec, added to the beam major-axis FWHM to
        determine the extent of the image region.
    pts_bw_nodes : int
        The number of points between each interpolation node.
        Must be non-negative.

    Returns
    -------
    bytes
        PNG image bytes containing the interpolated thumbnail.

    Raises
    ------
    ValueError
        If `pts_bw_nodes` is negative, if FITS image data is not a 3D array
        containing a 2D image, or if the selected image region is empty.

    References
    ----------
    .. [1] R. G. Keys, "Cubic Convolution Interpolation for Digital Image
       Processing," IEEE Transactions on Acoustics, Speech, and Signal
       Processing, 29(6), 1153-1160, 1981.
    """
    if pts_bw_nodes < 0:
        raise ValueError(
            "pts_bw_nodes must be non-negative. "
            f"Got {pts_bw_nodes}."
        )

    fits_file = Path(fits_file)
    hdu_index = _fits_data_index(fits_file)

    # Extract image data array and header from FITS file.
    with fits.open(fits_file) as hdulist:
        image_hdu = hdulist[hdu_index]
        data = image_hdu.data
        header_data = image_hdu.header

    if data.ndim != 3 or data.shape[0] != 1:
        raise ValueError(
            "FITS image data must be a 3D array containing a 2D image."
        )
    data_array = data[0]

    min_flux = np.min(data_array)
    max_flux = np.max(data_array)

    beam_maj = Angle(
        header_data['BMAJ'],
        header_data['CUNIT1']
    ).to_value('arcsec')
    pixel_scale = Angle(
        abs(header_data['CDELT1']),
        header_data['CUNIT1']
    ).to_value('arcsec')
    x_dim = header_data['NAXIS1']
    y_dim = header_data['NAXIS2']

    center = ((x_dim - 1) / 2, (y_dim - 1) / 2)

    # Convert source offsets from arcsec to absolute pixel coordinates.
    abs_x = round((peak_coord[0] / pixel_scale) + center[0])
    abs_y = round((peak_coord[1] / pixel_scale) + center[1])

    # Convert the search radius from arcsec to pixels, rounded up.
    delta = math.ceil((radius_buffer + beam_maj) / pixel_scale)

    # Restrict the image to a box centered on the source, clipped to the
    # original image boundaries.
    y_start = max(abs_y - delta, 0)
    y_stop = min(abs_y + delta, y_dim)
    x_start = max(abs_x - delta, 0)
    x_stop = min(abs_x + delta, x_dim)

    new_data = data_array[y_start:y_stop, x_start:x_stop]

    y_length, x_length = new_data.shape
    if y_length == 0 or x_length == 0:
        raise ValueError(
            "Attempts to obtain a smaller image centered on the source "
            "resulted in an empty data array."
        )
    node_x = np.arange(0, x_length).tolist()
    node_y = np.arange(0, y_length).tolist()

    interpolated_data = []

    # Apply Keys cubic convolution interpolation in the x-direction.
    pts_spacing = 1 / (pts_bw_nodes + 1)
    for row_num in range(y_length):
        temp = new_data[row_num].tolist()
        for i in range(x_length - 1):
            temp2 = []
            for j in range(1, pts_bw_nodes + 1):
                x = i + j * pts_spacing
                temp2.append(
                    _interpolation_function(
                        x,
                        node_x=node_x,
                        node_val=new_data[row_num]
                    )
                )
            temp = temp[:i - x_length + 1] + temp2 + temp[i - x_length + 1:]
        interpolated_data.append(temp)

    # Apply Keys cubic convolution interpolation in the y-direction.
    new_x_length = len(interpolated_data[0])
    temp = []
    for i in range((y_length - 1) * pts_bw_nodes):
        temp.append([])
    for col_num in range(new_x_length):
        temp2 = [row[col_num] for row in interpolated_data]
        for i in range(y_length - 1):
            for j in range(1, pts_bw_nodes + 1):
                y = i + j * pts_spacing
                temp[i * pts_bw_nodes + j - 1].append(
                    _interpolation_function(
                        y,
                        node_x=node_y,
                        node_val=temp2
                    )
                )
    for i in range(y_length - 1):
        interpolated_data = (
            interpolated_data[:i - y_length + 1]
            + temp[:pts_bw_nodes]
            + interpolated_data[i-y_length+1:]
        )
        temp = temp[pts_bw_nodes:]

    fig, ax = plt.subplots()
    ax.axis("off")
    ax.set_title(
        "Arcsec offset from center: {},\n pixel scale: {} arcsec".format(
            (round(peak_coord[0], 2), round(peak_coord[1], 2)),
            round(pixel_scale, 2)
        )
    )
    img = ax.imshow(interpolated_data, vmin=min_flux, vmax=max_flux)
    fig.colorbar(img)

    buffer = io.BytesIO()
    fig.savefig(buffer, format='png')
    buffer.seek(0)
    plot_data = buffer.read()
    plt.close(fig)

    return plot_data


def make_catalog(
    fits_file: str | Path,
    threshold: float = 0.01,
    radius_buffer: float = 5.0,
    ext_threshold: float | None = None,
) -> dict | None:
    """
    Create a catalog of significant point sources detected in a FITS image.

    Parameters
    ----------
    fits_file : str | Path
        The path of the FITS file that contains the image.
    threshold : float, optional
        The maximum expected number of independent noise measurements with flux
        densities greater than or equal to an internal peak for the peak to be
        considered significant, assuming no source is present in the image.
    radius_buffer : float, optional
        The amount of buffer, in arcsec, to add to the beam FWHM to get the
        initial search radius.
    ext_threshold : float | None, optional
        The maximum expected number of independent noise measurements with flux
        densities greater than or equal to an external peak for the peak to be
        considered significant, assuming no source is present in the image.
        If no value is given, `1e-3`, `1e-6`, or `1e-12` is used, depending on
        the signal-to-noise ratio of the brightest internal peak calculated
        using the initial external-region RMS estimate.

    Returns
    -------
    dict
        Dictionary with keys of the form `Source1`, `Source2`, etc., labeling
        the significant internal and external sources found in the image. Each
        key is associated with a dictionary with the following keys:
        `FieldName` : str
            The name of the target object of the observation.
        `ObsDateTime` : str
            The date and time of the observation, in the format M-d-yy h:m:s.
        `Stationary` : bool
            Whether the source can be approximated as stationary.
        `FileName` : str
            The name of the FITS file that contains the image.
        `BeamMajAxis_arcsec` : float
            The restoring beam major axis, in arcsec, rounded to 3 decimal
            places.
        `BeamMinAxis_arcsec` : float
            The restoring beam minor axis, in arcsec, rounded to 3 decimal
            places.
        `BeamPosAngle_deg` : float
            The restoring beam position angle, in degrees, rounded to 3 decimal
            places.
        `Freq_GHz` : float | str
            The frequency at which the image data was recorded, in GHz, rounded
            to 3 decimal places, or `Not found` if the frequency cannot be
            determined.
        `FluxUncert_mJy` : float
            The uncertainty in flux density measurements, in mJy, rounded to 3
            decimal places.
        `Flux_mJy` : float
            The flux density of the source, in mJy, rounded to 3 decimal
            places.
        `RAUncert_arcsec` : float
            The uncertainty in Right Ascension of the source, in arcsec,
            rounded to 3 decimal places.
        `DecUncert_arcsec` : float
            The uncertainty in the Declination of the source, in arcsec,
            rounded to 3 decimal places.
        `RA` : str
            The Right Ascension of the source, in the format {h}h{m}m{s}s,
            where the seconds are rounded to 2 decimal places.
        `Dec` : str
            The Declination of the source, in the format {d}d{m}m{s}s, where
            the seconds are rounded to 2 decimal places.
        `Internal` : bool
            Whether the detected point source is in the initial search region.
        `Image` : bytes
            PNG image bytes containing the interpolated thumbnail.
    None
        If no significant sources are found.

    Raises
    ------
    ValueError
        If `CTYPE1` and `CTYPE2` do not describe one Right Ascension axis and
        one Declination axis, or if the Right Ascension and Declination axes
        have different units.

    Notes
    -----
    The restoring beam major and minor axes are assumed to use the angular
    units specified by `CUNIT1` and `CUNIT2`, respectively. The Right Ascension
    and Declination axes are required to have the same units.

    `FluxUncert_mJy` is taken from the most conservative RMS value in
    `summary()`.

    `RAUncert_arcsec` and `DecUncert_arcsec` are calculated using the restoring
    beam dimensions and the source SNR.
    """
    fits_file = Path(fits_file)

    summ = summary(
        fits_file=fits_file,
        radius_buffer=radius_buffer,
        ext_threshold=ext_threshold,
        silence_dict=False,
        plot=False
    )

    header_data = fits.getheader(fits_file)
    name = header_data['OBJECT']
    obs_date_time = header_data['DATE-OBS']
    bmaj = header_data['BMAJ']
    bmin = header_data['BMIN']
    bpa = header_data['BPA']
    ctype1 = header_data['CTYPE1'].upper()
    crval1 = header_data['CRVAL1']
    cunit1 = header_data['CUNIT1']
    ctype2 = header_data['CTYPE2'].upper()
    crval2 = header_data['CRVAL2']
    cunit2 = header_data['CUNIT2']
    ctype3 = header_data['CTYPE3'].upper()
    crval3 = header_data['CRVAL3']
    cunit3 = header_data['CUNIT3'].lower()

    if cunit1 != cunit2:
        raise ValueError("Axes have different units.")

    # Support frequency information stored either directly in the image header
    # or in a channel table extension.
    freq = 'Not found'
    if ctype3 == 'FREQ':
        if cunit3 == 'ghz':
            freq = round(crval3, 3)
        elif cunit3 == 'hz':
            freq = round(crval3 / 1e9, 3)  # Convert to GHz.
    elif ctype3 == 'CHANNUM':
        with fits.open(fits_file) as hdul:
            freq_col = hdul[1].columns[1]
            freq_unit = freq_col.unit.lower()
            if freq_col.name == 'Freq':
                if freq_unit == 'hz':
                    freq = round(hdul[1].data[0][1] / 1e9, 3)  # Convert to GHz.
                elif freq_unit == 'ghz':
                    freq = round(hdul[1].data[0][1], 3)

    # Interpret the beam axes using the corresponding celestial-axis units.
    beam_maj_axis = Angle(bmaj, cunit1)
    beam_min_axis = Angle(bmin, cunit2)
    bpa_rad = math.radians(bpa)

    # Solar System bodies require moving-source treatment and are not treated as
    # stationary targets.
    moving_objects = [
        'venus',
        'mars',
        'jupiter',
        'uranus',
        'neptune',
        'io',
        'europa',
        'ganymede',
        'callisto',
        'titan',
        'ceres',
        'vesta',
        'pallas',
        'juno'
    ]

    name_lower = name.lower()
    stationary = not any(
        re.search(rf"\b{re.escape(obj)}\b", name_lower)
        for obj in moving_objects
    )

    interesting_sources = {}
    field_info = {
        'FieldName': name,
        'ObsDateTime': obs_date_time,
        'FileName': fits_file.name,
        'Stationary': stationary,
        'BeamMajAxis_arcsec': round(
            float(beam_maj_axis.to(u.arcsec).value), 3
        ),
        'BeamMinAxis_arcsec': round(
            float(beam_min_axis.to(u.arcsec).value), 3
        ),
        'BeamPosAngle_deg': round(bpa, 3),
        'Freq_GHz': freq
    }

    field_info['FluxUncert_mJy'] = round(summ['conservative_rms'] * 1e3, 3)

    n_int_sources = len(summ['int_peak_val'])

    # A string value indicates that no significant external peaks were found.
    if isinstance(summ['ext_peak_val'], str):
        n_ext_sources = 0
    else:
        n_ext_sources = len(summ['ext_peak_val'])

    ra_index = 0
    dec_index = 1

    if 'RA' in ctype1:
        ra = crval1
    elif 'RA' in ctype2:
        ra = crval2
        ra_index = 1
    else:
        raise ValueError("No RA in image.")

    if 'DEC' in ctype1:
        dec = crval1
        dec_index = 0
    elif 'DEC' in ctype2:
        dec = crval2
    else:
        raise ValueError("No dec in image.")

    center = SkyCoord(ra, dec, unit=cunit1)

    def create_source_info(
        peak_value,
        peak_coord,
        internal,
    ):
        """Create catalog information for a detected point source."""
        info = field_info.copy()

        info['Flux_mJy'] = round(peak_value * 1000, 3)

        # Estimate positional uncertainties from the restoring beam and source
        # SNR.
        snr = peak_value / summ['conservative_rms']
        bmin_uncert = float(beam_maj_axis.to(u.arcsec).value / snr)
        bmaj_uncert = float(beam_min_axis.to(u.arcsec).value / snr)

        info['RAUncert_arcsec'] = round(
            bmin_uncert * abs(math.sin(bpa_rad))
            + bmaj_uncert * abs(math.cos(bpa_rad)),
            3
        )
        info['DecUncert_arcsec'] = round(
            bmaj_uncert * abs(math.sin(bpa_rad))
            + bmin_uncert * abs(math.cos(bpa_rad)),
            3
        )

        ra_offset = peak_coord[ra_index] * u.arcsec
        dec_offset = peak_coord[dec_index] * u.arcsec
        coord = center.spherical_offsets_by(ra_offset, dec_offset)

        ra_tuple = coord.ra.hms
        dec_tuple = coord.dec.dms

        info['RA'] = (
            f'{int(ra_tuple.h)}h{int(ra_tuple.m)}m'
            f'{round(float(ra_tuple.s), 2)}s'
        )
        info['Dec'] = (
            f'{int(dec_tuple.d)}d{abs(int(dec_tuple.m))}m'
            f'{abs(round(float(dec_tuple.s), 2))}s'
        )

        info['Internal'] = internal

        info['Image'] = thumbnail(
            fits_file=fits_file,
            peak_coord=peak_coord,
            radius_buffer=radius_buffer,
            pts_bw_nodes=4,
        )

        return info


    pt_source_count = 1
    # Create catalog dictionary for each significant internal source.
    for i in range(n_int_sources):
        if (
            summ['int_exp_exceed'][i] < threshold
            and summ['calc_int_exp_exceed'][i] < threshold
        ):
            key = f'Source{pt_source_count}'
            interesting_sources[key] = create_source_info(
                summ['int_peak_val'][i],
                summ['int_peak_coord'][i],
                internal=True,
            )
            pt_source_count += 1

    # Create catalog dictionary for each external source.
    for i in range(n_ext_sources):
        key = f'Source{pt_source_count}'
        interesting_sources[key] = create_source_info(
            summ['ext_peak_val'][i],
            summ['ext_peak_coord'][i],
            internal=False,
        )
        pt_source_count += 1

    if not interesting_sources:
        return None

    return interesting_sources


def combine_catalogs(
    catalog_1: dict,
    catalog_2: dict,
) -> dict:
    """
    Combine two catalogs returned by `make_catalog()`.

    Entries from `catalog_2` are added to `catalog_1` with their source
    numbers shifted to follow the entries already present in `catalog_1`.
    `catalog_1` is modified in place.

    Parameters
    ----------
    catalog_1 : dict
        Catalog to which the entries from `catalog_2` are added. This
        dictionary is modified in place.
    catalog_2 : dict
        Catalog whose entries are added to `catalog_1`.

    Returns
    -------
    dict
        The combined catalog. This is the same dictionary object as
        `catalog_1`.
    """
    shift = len(catalog_1)
    for key, value in catalog_2.items():
        new_number = int(key.replace('Source', ''))
        new_key = f'Source{new_number + shift}'
        catalog_1[new_key] = value
    return catalog_1


def low_level_table(folder: str, db_path: str = '../sources.db'):
    """Create table of

    """
    str_obs_id = 'Unknown'
    big_catalog = None

    # Retrieve numerical SMA observation ID from folder name.
    try:
        str_obs_id = folder.replace('/mnt/COMPASS9/sma/quality/', '')
        obs_id = str_obs_id.replace('/', '')
        obs_id = int(obs_id) # Exception thrown if obs_id isn't only numbers
    except Exception as e:
        obs_id = 'Unknown'
        warnings.warn(
            f"Error with obsID: {e}. "
            "Old/outdated data may not be deleted."
        )

    if os.path.exists(db_path):
        # Get all rows from existing low level table, if it exists.
        con1_established = False
        con1_closed = False
        old_data_cleared = False
        try:
            con1 = sqlite3.connect(db_path)
            con1_established = True
            cur1 = con1.cursor()
            cur1.execute(
                "DELETE FROM low_level WHERE ObsID='{}'".format(obs_id)
            )
            con1.commit()
            old_data_cleared = True
            con1.close()
            con1_closed = True
        except Exception as e:
            if con1_established and not con1_closed:
                con1.close()
                if (
                    not old_data_cleared
                    and not isinstance(e, sqlite3.OperationalError)
                ):
                    warnings.warn(
                        "Error removing old/outdated data from table "
                        f"\"low_level\" at {db_path}: {e}."
                    )

    for file in glob.glob(os.path.join(folder, '*.fits')):
        try:
            catalog = make_catalog(file)
            if catalog is not None:
                for value in catalog.values():
                    value['ObsID'] = obs_id
                    value['SourceID'] = 'Unknown'
                if big_catalog is None:
                    big_catalog = catalog
                else:
                    big_catalog = combine_catalogs(big_catalog, catalog)
        except Exception as e:
            print(f'Error for {file}: {e}')

    if big_catalog is not None:
        df = pd.DataFrame.from_dict(big_catalog)
        df = df.T

        # fixing rounding error where 60 appears in the seconds
        date_times = df['ObsDateTime'].tolist()
        df.drop(columns='ObsDateTime', inplace=True)
        for i in range(len(date_times)):
            dt = date_times[i]
            m_end = dt.rindex(':')
            s_start = m_end + 1
            if dt[s_start:] == '60':
                dt = dt[:s_start] + '0'
                fmt = '%m-%d-%y %H:%M'
                date_times[i] = (datetime.strptime(dt[:m_end], fmt) + timedelta(minutes=1)).strftime('%m-%d-%y %H:%M:%S')
        df['ObsDateTime'] = date_times

        # write into low level table
        con2_established = False
        con2_closed = False
        dtype={'FieldName': 'TEXT', 'FileName': 'TEXT', 'Stationary': 'INTEGER', 'BeamMajAxis_arcsec': 'REAL', \
               'BeamMinAxis_arcsec': 'REAL', 'BeamPosAngle_deg': 'REAL', 'Freq_GHz': 'REAL', 'FluxUncert_mJy': 'REAL', \
                'Flux_mJy': 'REAL', 'RAUncert_arcsec': 'REAL', 'DecUncert_arcsec': 'REAL', 'RA': 'TEXT', 'Dec': 'TEXT', \
                'Internal': 'INTEGER', 'Image': 'BLOB', 'ObsID': 'TEXT', 'SourceID': 'TEXT', 'ObsDateTime': 'TEXT'}
        try:
            con2 = sqlite3.connect(db_path)
            con2_established = True
            df.to_sql("low_level", con=con2, if_exists='append', index=False, dtype=dtype)
            con2.close()
            con2_closed = True
        except Exception as e:
            if con2_established and not con2_closed:
                con2.close()
            print(f'Error adding to table "low_level" at {db_path}: {e}')


def high_level_table(db_path: str = '../sources.db'):

    unique_sources = None

    if os.path.exists(db_path):
        # get all rows from low level and high level tables, if they exist
        con1_established = False
        con1_closed = False
        try:
            con1 = sqlite3.connect(db_path)
            con1_established = True
            low_df = pd.read_sql_query("SELECT * FROM low_level;", con1)
            if low_df.empty:
                raise ValueError('Table "low_level" is empty')
            unique_sources = pd.read_sql_query("SELECT * FROM high_level;", con1).to_dict(orient='list')
            con1.close()
            con1_closed = True
        except Exception as e:
            if con1_established and not con1_closed:
                con1.close()
            if not isinstance(e, pd.errors.DatabaseError):
                print(f'Error reading from database at {db_path}: {e}')
    else:
        raise OSError(f'Path {db_path} not found')

    #coarse matching
    for row in range(len(low_df)):
        if low_df['SourceID'].iloc[row] == 'Unknown': #check to make sure we didn't already do coarse matching
            if low_df['Stationary'].iloc[row]:
                if unique_sources is not None:
                    ra = low_df['RA'].iloc[row]
                    dec = low_df['Dec'].iloc[row]
                    coord1 = SkyCoord(ra, dec)
                    fwhm = low_df['BeamMajAxis_arcsec'].iloc[row]
                    source_ids = unique_sources['SourceID']
                    matched  = False
                    while not matched:
                        for i in range(len(source_ids)): #compare with each unique source
                            coord2 = SkyCoord(unique_sources['RA'][i], unique_sources['Dec'][i])
                            sep = coord1.separation(coord2)
                            fwhm2_val = float(unique_sources['FWHM_arcsec'][i])
                            max_sep = (fwhm * fwhm2_val)**(1/2) * u.arcsec
                            matched = (sep <= max_sep)
                            if matched:
                                low_df.loc[row, 'SourceID'] = source_ids[i]
                                break
                        break
                    if not matched:
                        num = 1
                        id_nums = [int(source_id.replace('id', '')) for source_id in unique_sources['SourceID']]
                        while num in id_nums:
                            num += 1
                        next_number = '0' * (4 - len(str(num))) + str(num)
                        next_id = f'id{next_number}'
                        source_ids.append(next_id)
                        unique_sources['RA'].append(ra)
                        unique_sources['Dec'].append(dec)
                        unique_sources['FWHM_arcsec'].append(fwhm)
                        low_df.loc[row, 'SourceID'] = next_id
                        unique_sources['AmbiguousTies'].append('Unknown')
                else:
                    ra = low_df['RA'].iloc[row]
                    dec = low_df['Dec'].iloc[row]
                    fwhm = low_df['BeamMajAxis_arcsec'].iloc[row]
                    unique_sources = {'SourceID': ['id0001'], 'RA': [ra], 'Dec': [dec], 'FWHM_arcsec': [fwhm], 'AmbiguousTies': ['Unknown']}
                    low_df.loc[row, 'SourceID'] = 'id0001'
            else:
                low_df.loc[row, 'SourceID'] = 'Not Stationary'

    #further refining matches
    new_sources = unique_sources.copy()
    refined = []
    to_skip = []
    for i in range(len(unique_sources['SourceID'])):
        temp_df = low_df[(low_df['SourceID']) == unique_sources['SourceID'][i]]
        ra_list = [Angle(ra, u.deg) for ra in temp_df['RA']]
        dec_list = [Angle(dec, u.deg) for dec in temp_df['Dec']]
        fwhm_list = [Angle(fwhm, u.arcsec) for fwhm in temp_df['BeamMajAxis_arcsec']]
        if len(unique_sources['SourceID']) > 1 and i not in to_skip:
            for j in range(i + 1, len(unique_sources['SourceID'])):
                if j not in to_skip:
                    temp_df2 = low_df[(low_df['SourceID']) == unique_sources['SourceID'][j]]
                    ra_list2 = [Angle(ra, u.deg) for ra in temp_df2['RA']]
                    dec_list2 = [Angle(dec, u.deg) for dec in temp_df2['Dec']]
                    fwhm_list2 = [Angle(fwhm, u.arcsec) for fwhm in temp_df2['BeamMajAxis_arcsec']]
                    new_ra_list = ra_list + ra_list2
                    new_dec_list = dec_list + dec_list2
                    new_fwhm_list = fwhm_list + fwhm_list2
                    num_pts = len(new_ra_list)
                    avg_ra = sum(new_ra_list) / num_pts
                    avg_dec = sum(new_dec_list) / num_pts
                    geo_avg_fwhm = math.prod(new_fwhm_list) ** (1/num_pts)
                    avg_pt = SkyCoord(avg_ra, avg_dec)
                    temp = 0
                    for pt in range(num_pts):
                        sep = avg_pt.separation(SkyCoord(new_ra_list[pt], new_dec_list[pt]))
                        if sep > geo_avg_fwhm / 2:
                            temp += 1
                    proportion = (num_pts - temp) / (num_pts)
                    if proportion == 1: #average point is a good representative for all points, same source
                        refined.append(new_sources['SourceID'][i])
                        #match found, update averages
                        hms_ra = avg_ra.hms
                        dms_dec = avg_dec.dms
                        str_ra = f'{int(hms_ra.h)}h{abs(int(hms_ra.m))}m{round(abs(hms_ra.s), 2)}s'
                        str_dec = f'{int(dms_dec.d)}d{abs(int(dms_dec.m))}m{round(abs(dms_dec.s), 2)}s'
                        new_sources['RA'][i] = str_ra
                        new_sources['Dec'][i] = str_dec
                        new_sources['FWHM_arcsec'][i] = round(geo_avg_fwhm.value, 3)
                        #get rid of "replaced" source in AmbiguousTies
                        for k in range(len(unique_sources['SourceID'])):
                            unique_sources['AmbiguousTies'][k] = unique_sources['AmbiguousTies'][k].replace(unique_sources['SourceID'][j], '')
                            unique_sources['AmbiguousTies'][k] = unique_sources['AmbiguousTies'][k].replace('__', '_')
                            if unique_sources['AmbiguousTies'][k][0] == '_':
                                unique_sources['AmbiguousTies'][k] = unique_sources['AmbiguousTies'][k][1:]
                            if unique_sources['AmbiguousTies'][k][-1] == '_':
                                unique_sources['AmbiguousTies'][k] = unique_sources['AmbiguousTies'][k][:-1]
                        #update low_df
                        indices = low_df.index[low_df['SourceID'] == unique_sources['SourceID'][j]]
                        low_df.loc[indices, 'SourceID'] = unique_sources['SourceID'][i]
                        to_skip.append(j)
                    elif proportion > 0.7: #average point is a good representative for over 70% but less than 100% of points, ambiguous
                        if new_sources['AmbiguousTies'][i] == 'Unknown' or new_sources['AmbiguousTies'][i] == 'None found':
                            new_sources['AmbiguousTies'][i] = unique_sources['SourceID'][j]
                        elif unique_sources['SourceID'][j] not in new_sources['AmbiguousTies'][i]:
                            new_sources['AmbiguousTies'][i] += '_{}'.format(unique_sources['SourceID'][j])
                        if new_sources['AmbiguousTies'][j] == 'Unknown' or new_sources['AmbiguousTies'][j] == 'None found':
                            new_sources['AmbiguousTies'][j] = unique_sources['SourceID'][i]
                        elif unique_sources['SourceID'][i] not in new_sources['AmbiguousTies'][j]:
                            new_sources['AmbiguousTies'][j] += '_{}'.format(unique_sources['SourceID'][i])
                    if new_sources['AmbiguousTies'][i] == 'Unknown':
                        new_sources['AmbiguousTies'][i] = 'None found'
                    if new_sources['AmbiguousTies'][j] == 'Unknown':
                        new_sources['AmbiguousTies'][j] = 'None found'
    to_skip.sort(reverse=True)
    for k in to_skip:
        del new_sources['SourceID'][k]
        del new_sources['RA'][k]
        del new_sources['Dec'][k]
        del new_sources['FWHM_arcsec'][k]
        del new_sources['AmbiguousTies'][k]

    #get averages for sources only matched with coarse matching
    for i in range(len(new_sources['SourceID'])):
        if new_sources['SourceID'][i] not in refined:
            temp_df = low_df[(low_df['SourceID']) == new_sources['SourceID'][i]]
            ra_list = [Angle(ra, u.deg) for ra in temp_df['RA']]
            dec_list = [Angle(dec, u.deg) for dec in temp_df['Dec']]
            fwhm_list = [Angle(fwhm, u.arcsec) for fwhm in temp_df['BeamMajAxis_arcsec']]
            num_pts = len(ra_list)
            avg_ra = sum(ra_list) / num_pts
            hms_ra = avg_ra.hms
            str_ra = f'{int(hms_ra.h)}h{abs(int(hms_ra.m))}m{round(abs(hms_ra.s), 2)}s'
            avg_dec = sum(dec_list) / num_pts
            dms_dec = avg_dec.dms
            str_dec = f'{int(dms_dec.d)}d{abs(int(dms_dec.m))}m{round(abs(dms_dec.s), 2)}s'
            geo_avg_fwhm = math.prod(fwhm_list) ** (1/num_pts)
            new_sources['RA'][i] = str_ra
            new_sources['Dec'][i] = str_dec
            new_sources['FWHM_arcsec'][i] = round(geo_avg_fwhm.value, 3)

    df = pd.DataFrame.from_dict(new_sources)

    # write into low and high level tables
    con2_established = False
    con2_closed = False
    try:
        con2 = sqlite3.connect(db_path)
        con2_established = True
        df.to_sql("high_level", con=con2, if_exists='replace', index=False)
        low_df.to_sql("low_level", con=con2, if_exists='replace', index=False)
        con2.close()
        con2_closed = True
    except Exception as e:
        if con2_established and not con2_closed:
            con2.close()
        print(f'Error adding to table(s) at {db_path}: {e}')


def light_curve(source_id: str, db_path: str = '../sources.db',\
                plot: bool = True, table: bool = True, save_path: str = ''):

    if os.path.exists(db_path):
        # get all rows from low level and high level tables, if they exist
        con1_established = False
        con1_closed = False
        try:
            con1 = sqlite3.connect(db_path)
            con1_established = True
            low_df = pd.read_sql_query("SELECT * FROM low_level;", con1)
            if low_df.empty:
                raise ValueError('Table "low_level" is empty')
            high_df = pd.read_sql_query("SELECT * FROM high_level;", con1)
            if high_df.empty:
                raise ValueError('Table "high_level" is empty')
            con1.close()
            con1_closed = True
        except Exception as e:
            if con1_established and not con1_closed:
                con1.close()
            print(f'Error reading from database at {db_path}: {e}')
    else:
        raise OSError(f'Path {db_path} not found')

    source_df = low_df[low_df['SourceID'] == source_id]

    if plot:
        fluxes = source_df['Flux_mJy'].to_list()
        flux_errs = source_df['FluxUncert_mJy'].to_list()
        flux_unit = 'mJy'
        if max(fluxes) > 1000:
            flux_unit = 'Jy'
            for i in range(len(fluxes)):
                fluxes[i] /= 1000
                flux_errs[i] /= 1000
        date_times = source_df['ObsDateTime'].tolist()
        fmt_str = '%m-%d-%y %H:%M:%S'
        date_times = [Time(datetime.strptime(dt, fmt_str), format='datetime', scale='utc').mjd for dt in date_times]

        freqs = source_df['Freq_GHz'].tolist()
        other = []
        small_milli = [] # 1.1-1.2mm
        large_milli = [] # 1.3-1.4mm
        micro = [] # 870µm
        for i in range(len(freqs)):
            if freqs[i] == 'Not found':
                other.append(i)
                pass
            else:
                try:
                    float_freq = float(freqs[i])
                    if float_freq > 241.77 and float_freq < 282.82: # 1.24-1.06mm
                        small_milli.append(i)
                    elif float_freq > 208.19 and float_freq < 237.93: # 1.44-1.26mm
                        large_milli.append(i)
                    elif float_freq > 333.10 and float_freq < 356.90: # 900-840µm
                        micro.append(i)
                    else:
                        other.append(i)
                except Exception as e:
                    print(f'Error while getting the frequencies for source {source_id}: {e}')
        other_dt = [date_times[a] for a in other]
        other_flx = [fluxes[a] for a in other]
        other_flx_err = [flux_errs[a] for a in other]
        sm_milli_dt = [date_times[b] for b in small_milli]
        sm_milli_flx = [fluxes[b] for b in small_milli]
        sm_milli_flx_err = [flux_errs[b] for b in small_milli]
        lg_milli_dt = [date_times[c] for c in large_milli]
        lg_milli_flx = [fluxes[c] for c in large_milli]
        lg_milli_flx_err = [flux_errs[c] for c in large_milli]
        micro_dt = [date_times[d] for d in micro]
        micro_flx = [fluxes[d] for d in micro]
        micro_flx_err = [flux_errs[d] for d in micro]

        plt.errorbar(sm_milli_dt, sm_milli_flx, yerr=sm_milli_flx_err, color='g', fmt='x', capsize=3, markersize=2,\
                    capthick=0.5, elinewidth=0.5, label='~1.1-1.2mm')
        plt.errorbar(lg_milli_dt, lg_milli_flx, yerr=lg_milli_flx_err, color='r', fmt='x', capsize=3, markersize=2,\
                    capthick=0.5, elinewidth=0.5, label='~1.3-1.4mm')
        plt.errorbar(micro_dt, micro_flx, yerr=micro_flx_err, color='b', fmt='x', capsize=3, markersize=2,\
                    capthick=0.5, elinewidth=0.5, label='~870µm')
        plt.errorbar(other_dt, other_flx, yerr=other_flx_err, color='k', fmt='x', capsize=3, markersize=2,\
                    capthick=0.5, elinewidth=0.5, label='Other/not found')

        plt.title(f'Source {source_id[2:]}')
        plt.xlabel('Modified Julian Date')
        plt.ylabel(f'Flux [{flux_unit}]')
        plt.legend()
        plt.ylim(bottom=0)

        if save_path != '':
            try:
                if save_path[-1] != '/':
                    save_path = save_path + '/'
                plt.savefig(f'{save_path}{source_id}.jpg')
            except:
                print('Error saving figure. Double check path entered.')

    if table:
        cal_df = source_df.copy()
        for col in cal_df.columns:
            if col not in ['ObsDateTime', 'ObsID', 'Flux_mJy', 'FluxUncert_mJy', 'Freq_GHz']:
                cal_df.drop(columns=col, inplace=True)
        snr_list = [round(float(cal_df['Flux_mJy'].to_list()[i] / cal_df['FluxUncert_mJy'].to_list()[i]), 2) for i in range(len(cal_df))]
        cal_df['SNR'] = snr_list
        fmt_str = '%m-%d-%y %H:%M:%S'
        mjd_list = [float(Time(datetime.strptime(dt, fmt_str), format='datetime', scale='utc').mjd) for dt in cal_df['ObsDateTime']]
        cal_df['MJD'] = mjd_list
        return cal_df


def clause_helper(column_name: str, parameter, other_type):
    phrase = ''
    if parameter is not None:
        if type(parameter) == list:
            if parameter:
                for i in range(len(parameter)):
                    if type(parameter[i]) != other_type:
                        raise TypeError(f'In order to write a condition for {column_name}, if input is a list, its elements must be of {other_type}.')
                    if i == 0:
                        phrase += ' ({} = "{}"'.format(column_name, parameter[i])
                    else:
                        phrase += ' OR {} = "{}"'.format(column_name, parameter[i])
            phrase += ')'
        elif type(parameter) == other_type:
            if type(parameter) == str:
                if not parameter.strip():
                    return ''
            phrase += f' ({column_name} = "{parameter}")'
        else:
            raise TypeError(f'In order to write a condition for {column_name}, input must be None, of type list, or of {other_type}.')
        if phrase:
            phrase += ' AND'
    return phrase


def search_low_level(db_path: str = '../sources.db', field_name = None, stationary = True, lower_freq = None, upper_freq = None,\
                    lower_flux = None, upper_flux = None, ra = None, dec = None, sep_lower = None, sep_upper = None,\
                    internal = None, obs_id = None, source_id = None, obs_dt_lower = None, obs_dt_upper = None,\
                    show_thumbnail: bool = True):

    where_clause = 'WHERE'
    where_clause += clause_helper(column_name='FieldName', parameter=field_name, other_type=str)
    if stationary is not None:
        where_clause += f' (Stationary = {stationary}) AND'
    if not (lower_flux is None or type(lower_flux) == float or type(lower_flux) == int):
        raise TypeError('Inputted lower bound for flux must be None, of type float, or of type int.')
    if not (upper_flux is None or type(upper_flux) == float or type(upper_flux) == int):
        raise TypeError('Inputted upper bound for flux must be None, of type float, or of type int.')
    if lower_flux is not None and upper_flux is not None:
        where_clause += f' (Flux_mJy BETWEEN {lower_flux} AND {upper_flux}) AND'
    elif lower_flux is not None:
        where_clause += f' (Flux_mJy >= {lower_flux})'
    elif upper_flux is not None:
        where_clause += f' (Flux_mJy <= {upper_flux})'
    if internal is not None:
        where_clause += f' (Internal = {internal}) AND'
    where_clause += clause_helper(column_name='ObsID', parameter=obs_id, other_type=str)
    where_clause += clause_helper(column_name='SourceID', parameter=source_id, other_type=str)

    if where_clause[-5:] == 'WHERE':
        where_clause = ''
    if where_clause[-4:] == ' AND':
        where_clause = where_clause[:-4]
    where_clause += ';'

    if os.path.exists(db_path):
        # connect and query
        con_established = False
        con_closed = False
        try:
            con = sqlite3.connect(db_path)
            con_established = True
            result_df = pd.read_sql_query(f'SELECT * FROM low_level {where_clause}', con)
            con.close()
            con_closed = True
        except Exception as e:
            if con_established and not con_closed:
                con.close()
            print(f'Error querying database at {db_path} : {e}')
    else:
        raise OSError(f'Path {db_path} not found')

    to_drop = []
    if not (lower_freq is None or type(lower_freq) == int or type(lower_freq) == float):
        raise TypeError('Inputted frequency lower bound must be None, of type int, or of type float.')
    if not (upper_freq is None or type(upper_freq) == int or type(upper_freq) == float):
        raise TypeError('Inputted frequency upper bound must be None, of type int, or of type float.')
    if lower_freq is not None and upper_freq is not None:
        for row in range(len(result_df)):
            if result_df['Freq_GHz'].iloc[row] == 'Not found':
                to_drop.append(row)
            elif not (float(result_df['Freq_GHz'].iloc[row]) <= upper_freq and float(result_df['Freq_GHz'].iloc[row]) >= lower_freq):
                to_drop.append(row)
        result_df.drop(to_drop, inplace=True)
    elif lower_freq is not None:
        for row in range(len(result_df)):
            if result_df['Freq_GHz'].iloc[row] == 'Not found':
                to_drop.append(row)
            elif not (float(result_df['Freq_GHz'].iloc[row]) >= lower_freq):
                to_drop.append(row)
        result_df.drop(to_drop, inplace=True)
    elif upper_freq is not None:
        for row in range(len(result_df)):
            if result_df['Freq_GHz'].iloc[row] == 'Not found':
                to_drop.append(row)
            elif not (float(result_df['Freq_GHz'].iloc[row]) <= upper_freq):
                to_drop.append(row)
        result_df.drop(to_drop, inplace=True)
    if to_drop and not result_df.empty:
        result_df.reset_index(inplace=True)

    # handling ra, dec stuff
    coord = None
    ra_ang = None
    dec_ang = None
    lower_ang = None
    upper_ang = None
    if sep_lower is not None:
        try:
            lower_ang = Angle(sep_lower)
            if lower_ang == 0:
                lower_ang = None
        except Exception as e:
            print(f'Error converting separation lower bound input to Angle: {e}')
    if sep_upper is not None:
        try:
            upper_ang = Angle(sep_upper)
            if upper_ang == 0:
                upper_ang = None
        except Exception as e:
            print(f'Error converting separation upper bound input to Angle: {e}')
    if lower_ang is not None and upper_ang is not None:
        if lower_ang > upper_ang:
            raise ValueError(f'Inputted separation lower bound {sep_lower} is greater than inputted separation upper bound {sep_upper}.')
    if ra is not None and dec is not None:
        try:
            coord = SkyCoord(ra, dec)
        except Exception as e:
            print(f'Error converting Right Ascension and Declination inputs to SkyCoord object: {e}')
    elif ra is not None:
        try:
            ra_ang = Angle(ra)
        except Exception as e:
            print(f'Error converting Right Ascension input to Angle: {e}')
    elif dec is not None:
        try:
            dec_ang = Angle(dec)
        except Exception as e:
            print(f'Error converting Declination input to Angle: {e}')

    to_drop = []
    if lower_ang is not None and upper_ang is not None:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                sep = coord.separation(temp_coord)
                if not (sep <= upper_ang and sep >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (abs(ra_ang - temp_ang) <= upper_ang and abs(ra_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (abs(dec_ang - temp_ang) <= upper_ang and abs(dec_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    elif lower_ang is not None:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                sep = coord.separation(temp_coord)
                if not (sep >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (abs(ra_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (abs(dec_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    elif upper_ang is not None:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                sep = coord.separation(temp_coord)
                if not (sep <= upper_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (abs(ra_ang - temp_ang) <= upper_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (abs(dec_ang - temp_ang) <= upper_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    else:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                if not (temp_coord == coord):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (temp_ang == ra_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (temp_ang == dec_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    if to_drop and not result_df.empty:
        result_df.reset_index(inplace=True)

    to_drop = []
    # handling observation date time stuff
    lower_dt = None
    upper_dt = None
    fmt = '%m-%d-%y %H:%M:%S'
    if obs_dt_lower is not None:
        try:
            lower_dt = datetime.strptime(obs_dt_lower, fmt)
        except Exception as e:
            print(f'Error converting inputted observation date and time lower bound to datetime object: {e}. Please check the input format and ensure it matches {fmt}.')
    if obs_dt_upper is not None:
        try:
            upper_dt = datetime.strptime(obs_dt_upper, fmt)
        except Exception as e:
            print(f'Error converting inputted observation date and time upper bound input to datetime object: {e}. Please check the input format and ensure it matcheds {fmt}.')

    if lower_dt is not None and upper_dt is not None:
        if lower_dt > upper_dt:
            raise ValueError(f'Inputted observation date and time lower bound {obs_dt_lower} is later than inputted observation date and time upper bound {obs_dt_upper}.')
        for row in range(len(result_df)):
            temp_dt = datetime.strptime(result_df['ObsDateTime'].iloc[row], fmt)
            if not (temp_dt <= upper_dt and temp_dt >= lower_dt):
                to_drop.append(row)
        result_df.drop(to_drop, inplace=True)
    elif lower_dt is not None:
        for row in range(len(result_df)):
            temp_dt = datetime.strptime(result_df['ObsDateTime'].iloc[row], fmt)
            if not (temp_dt >= lower_dt):
                to_drop.append(row)
        result_df.drop(to_drop, inplace=True)
    elif upper_dt is not None:
        for row in range(len(result_df)):
            temp_dt = datetime.strptime(result_df['ObsDateTime'].iloc[row], fmt)
            if not (temp_dt <= upper_dt):
                to_drop.append(row)
        result_df.drop(to_drop, inplace=True)
    if to_drop and not result_df.empty:
        result_df.reset_index(inplace=True)

    if result_df.empty:
        print('Search returned an empty table.')
    else:
        if 'level_0' in result_df:
            result_df.drop(columns='level_0', inplace=True)
        if 'index' in result_df:
            result_df.drop(columns='index', inplace=True)

    if show_thumbnail:
        image_data = result_df['Image']
        for thumbnail in image_data:
            image_buffer = io.BytesIO(thumbnail)
            image = Image.open(image_buffer)
            image.show()
    return result_df


def search_high_level(db_path: str = '../sources.db', source_id = None, ra = None, dec = None, sep_lower = None, sep_upper = None,\
                      ambiguous_ties = None, ambig_exact: bool = False):
    where_clause = 'WHERE'
    where_clause += clause_helper(column_name='SourceID', parameter=source_id, other_type=str)

    if where_clause[-5:] == 'WHERE':
        where_clause = ''
    if where_clause[-4:] == ' AND':
        where_clause = where_clause[:-4]
    where_clause += ';'

    if os.path.exists(db_path):
        # connect and query
        con_established = False
        con_closed = False
        try:
            con = sqlite3.connect(db_path)
            con_established = True
            result_df = pd.read_sql_query(f'SELECT * FROM high_level {where_clause}', con)
            con.close()
            con_closed = True
        except Exception as e:
            if con_established and not con_closed:
                con.close()
            print(f'Error querying database at {db_path} : {e}')
    else:
        raise OSError(f'Path {db_path} not found')

    # handling ra, dec stuff
    coord = None
    ra_ang = None
    dec_ang = None
    lower_ang = None
    upper_ang = None
    if sep_lower is not None:
        try:
            lower_ang = Angle(sep_lower)
            if lower_ang == 0:
                lower_ang = None
        except Exception as e:
            print(f'Error converting separation lower bound input to Angle: {e}')
    if sep_upper is not None:
        try:
            upper_ang = Angle(sep_upper)
            if upper_ang == 0:
                upper_ang = None
        except Exception as e:
            print(f'Error converting separation upper bound input to Angle: {e}')
    if lower_ang is not None and upper_ang is not None:
        if lower_ang > upper_ang:
            raise ValueError(f'Inputted separation lower bound {sep_lower} is greater than inputted separation upper bound {sep_upper}.')
    if ra is not None and dec is not None:
        try:
            coord = SkyCoord(ra, dec)
        except Exception as e:
            print(f'Error converting Right Ascension and Declination inputs to SkyCoord object: {e}')
    elif ra is not None:
        try:
            ra_ang = Angle(ra)
        except Exception as e:
            print(f'Error converting Right Ascension input to Angle: {e}')
    elif dec is not None:
        try:
            dec_ang = Angle(dec)
        except Exception as e:
            print(f'Error converting Declination input to Angle: {e}')

    to_drop = []
    if lower_ang is not None and upper_ang is not None:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                sep = coord.separation(temp_coord)
                if not (sep <= upper_ang and sep >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (abs(ra_ang - temp_ang) <= upper_ang and abs(ra_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (abs(dec_ang - temp_ang) <= upper_ang and abs(dec_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    elif lower_ang is not None:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                sep = coord.separation(temp_coord)
                if not (sep >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (abs(ra_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (abs(dec_ang - temp_ang) >= lower_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    elif upper_ang is not None:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                sep = coord.separation(temp_coord)
                if not (sep <= upper_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (abs(ra_ang - temp_ang) <= upper_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (abs(dec_ang - temp_ang) <= upper_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    else:
        if coord is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_dec = result_df['Dec'].iloc[row]
                temp_coord = SkyCoord(temp_ra, temp_dec)
                if not (temp_coord == coord):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif ra_ang is not None:
            for row in range(len(result_df)):
                temp_ra = result_df['RA'].iloc[row]
                temp_ang = Angle(temp_ra)
                if not (temp_ang == ra_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
        elif dec_ang is not None:
            for row in range(len(result_df)):
                temp_dec = result_df['Dec'].iloc[row]
                temp_ang = Angle(temp_dec)
                if not (temp_ang == dec_ang):
                    to_drop.append(row)
            result_df.drop(to_drop, inplace=True)
    if to_drop and not result_df.empty:
        result_df.reset_index(inplace=True)

    to_drop = []
    if ambiguous_ties is not None:
        if type(ambiguous_ties) == bool:
            if ambiguous_ties:
                for row in range(len(result_df)):
                    if result_df['AmbiguousTies'].iloc[row] == 'None found':
                        to_drop.append(row)
                result_df.drop(to_drop, inplace=True)
            elif not ambiguous_ties:
                for row in range(len(result_df)):
                    if result_df['AmbiguousTies'].iloc[row] != 'None found':
                        to_drop.append(row)
                result_df.drop(to_drop, inplace=True)
        elif ambig_exact:
            if type(ambiguous_ties) == list:
                if ambiguous_ties:
                    try:
                        ambiguous_ties = [ele.strip() for ele in ambiguous_ties]
                    except AttributeError:
                        if type(ambiguous_ties) == str:
                            raise AttributeError
                        else:
                            raise TypeError('In order to search by ambiguous ties, if input is a list, its elements must be of type str.')
                    for row in range(len(result_df)):
                        temp = result_df['AmbiguousTies'].iloc[row]
                        for ele in ambiguous_ties:
                            if ele not in temp:
                                to_drop.append(row)
                            temp = temp.replace(ele, '')
                        if temp.replace('_', ''): # this means there are source IDs in temp that are not in ambiguous_ties
                            if row not in to_drop:
                                to_drop.append(row)
                    result_df.drop(to_drop, inplace=True)
            elif type(ambiguous_ties) == str:
                ambiguous_ties = ambiguous_ties.strip()
                if ambiguous_ties:
                    for row in range(len(result_df)):
                        temp = result_df['AmbiguousTies'].iloc[row]
                        if ambiguous_ties != temp:
                            to_drop.append(row)
                    result_df.drop(to_drop, inplace=True)
            else:
                raise TypeError('In order to search by ambiguous ties, input must be None, of type list, or of type str.')
        elif not ambig_exact:
            if type(ambiguous_ties) == list:
                if ambiguous_ties:
                    try:
                        ambiguous_ties = [ele.strip() for ele in ambiguous_ties]
                    except AttributeError:
                        if type(ambiguous_ties) == str:
                            raise AttributeError
                        else:
                            raise TypeError('In order to search by ambiguous ties, if input is a list, its elements must be of type str.')
                    for row in range(len(result_df)):
                        temp = result_df['AmbiguousTies'].iloc[row]
                        for ele in ambiguous_ties:
                            if ele in temp:
                                continue
                            to_drop.append(row)
                    result_df.drop(to_drop, inplace=True)
            elif type(ambiguous_ties) == str:
                ambiguous_ties = ambiguous_ties.strip()
                if ambiguous_ties:
                    for row in range(len(result_df)):
                        temp = result_df['AmbiguousTies'].iloc[row]
                        if ambiguous_ties not in temp:
                            to_drop.append(row)
                    result_df.drop(to_drop, inplace=True)
    if to_drop and not result_df.empty:
        result_df.reset_index(inplace=True)

    if result_df.empty:
            print('Search returned an empty table.')
    else:
        if 'level_0' in result_df:
            result_df.drop(columns='level_0', inplace=True)
        if 'index' in result_df:
            result_df.drop(columns='index', inplace=True)
    return result_df
